repos:
- hooks:
  - args:
    - --baseline
    - .baseline
    exclude: go.mod|go.sum
    id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets.git
  rev: v1.2.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.27.1
- hooks:
  - id: golangci-lint
  repo: https://github.com/golangci/golangci-lint
  rev: v1.45.2
